<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('products')->insert([
			['id' => 1, 'name' => 'Cannondale F29 Carbon 4', 'price' => 879000, 'description' => '<p class="p1">Conocemos a muchos ciclistas que están interesados ​​en poner a prueba sus piernas en las carreras de cross country, pero se sienten intimidados por el costo de una bicicleta digna de una carrera. Han dado una oportunidad a sus series de carreras locales en sus confiables bicicletas de trail y ahora están buscando una bicicleta de fondo para acercarlos un paso más al chorro de champán. Pueden entrar a una tienda de bicicletas local con la esperanza de llevar a casa un boleto de oro al podio, pero las etiquetas de precio que cuelgan de los bares de la mayoría de las bicicletas de carreras de cross los asustan de nuevo en sus bicicletas de trail de 5 pulgadas. Cannondale es conocido por producir máquinas que llevan a los jinetes a las victorias en el campeonato, pero Cannondale no se ha olvidado de los corredores de nivel de entrada. El alto rendimiento y la asequibilidad son características importantes del Cannondale F29 Carbon 4.</p>
   <h2 class="p1"><strong>¿PARA QUIÉN ESTÁ HECHO?</strong></h2>
   <p class="p4">Probablemente escuchaste sobre la serie de carreras locales a través de un par de amigos en la oficina. Te convencieron para que pasaras una tarde y terminaste gritando de apoyo hasta que te dolieron las cuerdas vocales. La semana siguiente apareciste en la carrera con tu bicicleta de trail diaria y les dijiste a tus amigos que estabas allí simplemente "tómalo con calma", pero despertó tu impulso competitivo y entraste en la próxima carrera decidido a superar a los pocos muchachos que habían terminado después de ti. Una cosa llevó a la siguiente, y ahora estás parado frente a largas hileras de bicicletas elegantes en tu tienda de bicicletas local en busca de una bicicleta de carreras liviana que no requiera que ingreses en el fondo universitario de tu hijo. La F29 Carbon 4 es la bicicleta para ti.</p>
   <h2 class="p3"><strong>¿DE QUE ESTA HECHO?</strong></h2>
   <p class="p4">Carbon se ha convertido en el campeón indiscutible de las victorias en carreras a campo traviesa. Cannondale se aseguró de mantenerse al día con los Jones, por lo que el F29 Carbon 4 tiene un diseño de cuadro ultraligero que no sacrifica la rigidez. Las fibras ininterrumpidas recorren toda la longitud de la bicicleta, desde el tubo de dirección hasta las punteras, proporcionando una rigidez óptima en un paquete liviano. La tecnología Speed ​​Save en el triángulo trasero proporciona una micro suspensión sin pivote integrada tanto en el asiento como en las vainas. Cada uno de estos tubos está esencialmente ovalado en el medio, lo que permite que el triángulo trasero tenga un poco de flexibilidad / flexibilidad vertical sin comprometer la rigidez de lado a lado. Cannondale afirma que su tecnología Speed ​​Save ayuda a que la rueda trasera abrace el suelo y aumenta la aceleración, todo mientras reduce la fatiga del conductor.</p>
   <p class="p4">Es imposible mirar el F29 Carbon 4 y no dejar que sus ojos vayan directamente a la horquilla Lefty 100 PBR. Las horquillas zurdas solo se encuentran en las bicicletas de los ciclistas que están comprometidos con su experiencia de conducción, y la horquilla inmediatamente distingue a la bicicleta de cualquiera de sus competidores. Las ruedas ZTR Rapid de Stan proporcionan el ahorro de peso que deseamos en una bicicleta de carrera a campo traviesa sin costar un brazo y una pierna. Los efectos de goteo de la tecnología tienen componentes Shimano SLX que rivalizan con el rendimiento de muchos componentes XT e incluso XTR, por lo que nos complace encontrar que el cambio Shimano SLX cambia a través de las marchas por nosotros.</p>
   
   <h1 class="p3"><strong>¿CÓMO FUNCIONA?</strong></h1>
   <h3 class="p4"><b>Mudarse:</b></h3>
   <p class="gt-block p4">Descubrimos las ventajas y desventajas de la horquilla Lefty en nuestro primer viaje en el F29 Carbon 4. Primero, salimos de la oficina y nos dimos cuenta de que no teníamos forma de asegurar la bicicleta a la configuración del soporte de la horquilla en nuestro automóvil. Sí, varias compañías fabrican adaptadores de horquilla Lefty, pero eso significa que el adaptador debe acompañar a la bicicleta donde quiera que vaya. Además, se debe quitar la pinza de freno para quitar la rueda delantera y luego volver a colocarla para asegurarse de que no esté sonando. Transportar la bicicleta es una molestia, pero no es el fin del mundo. Curiosamente, sacar a la luz una llanta desinflada es una ventaja que a menudo se pasa por alto de una horquilla Lefty. Es bueno no tener que quitar la rueda de la horquilla para reemplazar un tubo, y el tiempo que podría ahorrar durante una carrera podría ser suficiente para que un piloto vuelva al curso antes de que sus oponentes lo alcancen.<span class="Apple-converted-space"> </span></p>
   <h3 class="p4"><b>Alpinismo:</b></h3>
   <p class="p4">La eficiencia es el nombre del juego con el F29 Carbon 4, y nuestras piernas lo notaron en nuestros días más largos en la silla de montar. Estamos alimentados de una jerga de marketing interminable que dice lo que harán las bicicletas, pero preferimos confiar en la forma en que nuestras piernas se sienten después de días de cambio de elevación de 5000 pies, y esta bicicleta dejó nuestras piernas como un millón de dólares. Es raro subirse a una bicicleta y sentir que cada onza de músculo se usa de manera eficiente, pero así es como nos sentimos en el F29 Carbon 4. Además, fue increíblemente ágil en golpes técnicos donde se requería saltar o superar obstáculos.</p>
   <h3 class="p4"><b>Curvas </b></h3>
   <p class="p4">Incluso para una bicicleta de carrera de fondo, el ángulo del tubo de dirección de 71 grados y la distancia entre ejes de 44.2 pulgadas son, respectivamente, empinadas y cortas. Como resultado, el F29 Carbon 4 se abrió camino a través de las curvas cerradas con facilidad. La combinación también nos permitió saltar como cabras montesas a través de cualquier curva técnica de baja velocidad. Por otro lado, nos encontramos empujando nuestro peso sobre el neumático trasero para mantener la estabilidad durante las curvas de alta velocidad. Notamos que los beneficios del Speed ​​Save se mantienen más al salir de las curvas que necesitan algunas velocidades adicionales. Mientras nuestros neumáticos pudieran encontrar carne en el camino, pudimos acelerar de cada esquina a un sprint sin perder tracción.</p>
   <h3 class="p4"><b>Descendente: </b></h3>
   <p class="p4">Ciertamente no quisiéramos encontrarnos martillando a través de secciones gruesas de sendero sin tener nuestros dedos pegados a los frenos, pero la bicicleta ciertamente fue capaz cuando nuestra elección de línea era acertada. Incluso con las grandes ruedas de 29 pulgadas y 100 milímetros de recorrido de la horquilla, el tubo de dirección empinado permitió obstáculos altos para detener abruptamente el neumático delantero. Simplemente nos hizo centrarnos más en dónde colocamos nuestro neumático delantero y nos hizo pensar en términos de la mejor línea en lugar de la línea más directa. Afortunadamente, el F29 Carbon 4 tuvo mucha diversión en el banco y nos brindó una gran capacidad de respuesta para que despegáramos el neumático delantero del suelo en cualquier momento.</p>
    <h3 class="p4"><b>Frenado: </b></h3>
   <p class="p4">Los frenos Shimano Deore proporcionan una gran potencia de frenado para la mayoría de las aplicaciones de campo traviesa. Se bloquean con el tirón de un solo dedo y se niegan a soltar el rotor. El único inconveniente es la tendencia a desvanecerse en descensos largos, pero nuestros descensos fueron más largos que los que se encuentran típicamente en los hipódromos para los que el F29 Carbon 4 sería más adecuado.</p>
   <h2 class="p3"><strong>¿TRUCOS, ACTUALIZACIONES O CONSEJOS?</strong></h2>
   <p class="p4">Bombeamos 10 psi adicionales de presión en la horquilla sobre lo que sugería la carta de aire del fabricante. Aunque significaba que no usamos todo el viaje en algunos paseos, proporcionó una plataforma más estable en el extremo superior del recorrido de la horquilla. Si las guías del cable de freno en la horquilla no están colocadas correctamente, pueden causar chirridos cuando la horquilla está comprimida. Simplemente gire la guía superior más cerca del borde exterior de la horquilla y esto debería resolver el problema. Los neumáticos Schwalbe Racing Ralph proporcionaron una amplia tracción mientras tenían el caucho para hacerlo, pero se desgastaron rápidamente en algunos paseos. Los neumáticos Kenda Small Block Eight tienen un dibujo de la banda de rodadura muy similar, pero tienden a durar un poco más.</p>',
		'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
		'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
		],
	]);

    }
}

